### ISSUE TITLE
Основные варианты использования приложения?

### ISSUE THREAD

**Issue by w3prog** [dartl/IS_ScientificWork#1]

**Comment by w3prog** [comment]
Не мой репозиторий, но мне как куратору важно знать это.

**Comment by krinkin** [comment]
из информации, приведенной на странице http://se.moevm.info/doku.php/start

> Приложение должно предоставлять возможность 
> ввода/обработки/хранения/предоставление информации о:
>  - публикациях/научных трудах (группировка по годам/людям)
>  - участии (достижениях) в конференциях/конкурсах/НИОКР и т.д.
>  - численности аспирантов, докторантов, соискателей и стажеров
>  - Также приложение должно обеспечивать разные уровни доступа к информации для 
>  - различных пользователей.

можно довольно легко (по крайне мере на мой взгляд) сформулировать функциональные требования и варианты использования:

- CRUD информации  о публикациях/научных трудах
- CRUD участии (достижениях) в конференциях/конкурсах/НИОКР
- CRUD численности аспирантов, докторантов, соискателей и стажеров
- Просмотр с группировкой по годам/людям
- Аутентификация и авторизация
